
version: 0.2
env:
  variables:
    SRC: deploy.py
#   exported-variables:
#     - PREP_JOB_NAME
#     - TRAIN_JOB_NAME
#     - EVAL_JOB_NAME
#     - TRAINED_MODEL_S3

phases:
  install:
    runtime-versions:
      # docker: 18
      python: 3.8
    commands:
      - pip install -r requirements-deploy.txt

  build:
    commands:
      # Set Environment Variables from flow.yml
#       - . ./setenv.sh
      # Build Docker images and push to ECR
#       - . ./ml-pipeline/ecr-regist-images.sh
      # Execute ML workflow
      - python $SRC
